
#https://docs.python.org/3/py-modindex.html


import math

print(math.pi) # returns math pi - use this not 3.14.... becasuer of floating point precision issues
print(math.e)

print(math.sqrt(2.0))  # returns square root of a given number

print(math.sin(math.radians(90)))   # sin of 90 degrees

# -----------------------------------------------------------------
import random

prob = random.random() # math.random() - is a function call ramdom return of float between 0 and 1
print(prob)
result = prob * 5
print(result)

diceThrow = random.randrange(1, 7)       # return an int, one of 1,2,3,4,5,6 randomly
print(diceThrow)

# -----------------------------------------------------------------
# Counter randomly generate a numbers a particular number of times like 10

howmany = 10
for counter in range(howmany):
    arandom = random.random()
    print(arandom)

#-----------------------------------------------------------------------

""" Questions got wrong on homework and tests."""

""" Last homework assignemt -  multiple choice: 

Question 1:  Select the Python math module function that give you the Euclidean norm, square root of 
x*x + y*y. This is the length of the vector from the origin to point (x, y).
    
    answer: hypot

Question 7:   What Python line(s) of code that guarantee to give a random integer only 
between 10 and 100 inclusive both ends?
    
    answers: 
        - 10+ int(91*random.random()) 
        - random.randint(10, 100)     -------- ? double check
        - random.randrange(10, 101)

Question 10:   Select all the lines of code that give you the sine value of the angle 150 degrees. 
You can presume you already imported the math module with the command import math.
    
    answers:
        - math.sin(math.radians(150))
        - math.sin(math.pi*5/6) 

"""


# -----------------------------------------------------------------

# Module index:
    # https://docs.python.org/3/py-modindex.html

# Order of Precedence:
    # *, +, !=, >=, not, and 


# Vacabulary to know for imports:
    # import math       -  is a module
    # import random - or if you just need random and not the entire math module use this
    # math.random() - is a function call ramdom return of float between 0 and 1
    # math.randrange(x,y) returns value of randomly generated number given two numer eg: 1 and 7 
    # random.seed(a=None, version=2) -
    
# Glossery
    # deterministic - A process that is repeatable and predictable. 
    # documentation - A place where you can go to get detailed information about aspects of your programming language.
    # inf - infinity
    # Mersenne Twister -extensively tested random number generators - it is deterministic -not suitable for all purpose
    #        - completely unsuitable for cryptographic purposes.
    # module - A file containing Python definitions and statements intended for use in other Python programs. 
    #        - The contents of a module are made available to the other program by using the import statement.
    # NaN - Not a Number
    # pseudo-random number - A number that is not genuinely random but is instead created algorithmically. 
    # random number - A number that is generated in such a way as to exhibit statistical randomness.
    #       - they are not genuinely random
    #       - If we use same seed value we may get same random number
    #       - a seed value generated by system time would be a good choice
    # random number generator -A function that will provide you with random numbers, usually 
    #        - between 0 and 1.
    # standard library - A collection of modules that are part of the normal installation of Python.


