import math

print(math.pi) # returns math pi - use this not 3.14.... becasuer of floating point precision issues
print(math.e)

print(math.sqrt(2.0))  # returns square root of a given number

print(math.sin(math.radians(90)))   # sin of 90 degrees

# -----------------------------------------------------------------
import random

prob = random.random() # math.random() - is a function call ramdom return of float between 0 and 1
print(prob)
result = prob * 5
print(result)

diceThrow = random.randrange(1, 7)       # return an int, one of 1,2,3,4,5,6 randomly
print(diceThrow)

# -----------------------------------------------------------------
# Counter randomly generate a numbers a particular number of times like 10

howmany = 10
for counter in range(howmany):
    arandom = random.random()
    print(arandom)


# -----------------------------------------------------------------

# Module index
    # https://docs.python.org/3/py-modindex.html

# Vacabulary to know for imports:
    # import math       -  is a module
    # import random - or if you just need random and not the entire math module use this
    # math.random() - is a function call ramdom return of float between 0 and 1
    # math.randrange(x,y) returns value of randomly generated number given two numer eg: 1 and 7 
    # random.seed(a=None, version=2) -
    
# Glossery
    # deterministic - A process that is repeatable and predictable. 
    # documentation - A place where you can go to get detailed information about aspects of your programming language.
    # inf - infinity
    # Mersenne Twister -extensively tested random number generators - it is deterministic -not suitable for all purpose
    #        - completely unsuitable for cryptographic purposes.
    # module - A file containing Python definitions and statements intended for use in other Python programs. 
    #        - The contents of a module are made available to the other program by using the import statement.
    # NaN - Not a Number
    # pseudo-random number - A number that is not genuinely random but is instead created algorithmically. 
    # random number - A number that is generated in such a way as to exhibit statistical randomness.
    #       - they are not genuinely random
    #       - If we use same seed value we may get same random number
    #       - a seed value generated by system time would be a good choice
    # random number generator -A function that will provide you with random numbers, usually 
    #        - between 0 and 1.
    # standard library - A collection of modules that are part of the normal installation of Python.


